"🤖 bot":
  - any: "apps/bot/**"

"🖥️ website":
  - any: "apps/web/**"

"⚙️ actions":
  - any: ".github/workflows/**"

"📖 documentation":
  - any: ["apps/web/src/content/docs/**", "README.md", 'LICENSE', ".env.example", "config.example.yml"]
