name: PR Docgen

on:
  pull_request_target

jobs:
  commands:
    name: Generate Command Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.BOT_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        shell: bash
        run: bun install
      - name: Run generation script
        run: bun run docgen:commands
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: "apps/web/src/registry"
          author_name: CosmoticRovee
          author_email: cosmoticrovee@users.noreply.github.com
          message: "ci: update command docs"
